### PR TITLE
fix #2751 - Media not rendered when Converse runs in a browser extension

### LINKED ISSUE #2751: Media not rendered when Converse runs in a browser extension
**Describe the bug**
When Converse is run inside a Chrome or Edge extension, **window.location.protocol** return "chrome-extension:". This causes the checkFileTypes  method to return false.
See https://github.com/conversejs/converse.js/blob/6cff47c6d8ff028c31b650f6c8dbf1ef85a1f194/src/headless/utils/url.js#L24

**To Reproduce**
1. Run ConverseJs in a Chrome extension and upload an image.
2. Image is not rendered. Instead the image URL is turned into a clickable URL

**Expected behavior**
Image to be rendered

**Screenshots**

image

**Environment (please complete the following information):**
 - Desktop 
 - Browser Chrome and Edge browser extensions
 - Converse.js version 9.0.0

**Additional context**
The screen shot was produced after hacking checkFileTypes and adding a test for 'chrome-extension:'
```
function checkFileTypes (types, url) {
    const uri = getURI(url);
    if (!window.location.protocol === 'chrome-extension:' && (uri === null || !checkTLS(uri))) {
        return false;
    }
    const filename = uri.filename().toLowerCase();
    return !!types.filter(ext => filename.endsWith(ext)).length;
}
```

### PR DESCRIPTION
**Pull request by deleolajide**
Thanks for making a pull request to converse.js!

Before submitting your request, please make sure the following conditions are met:

- [x ] Add a changelog entry for your change in `CHANGES.md`
- [ ] When adding a configuration variable, please make sure to
      document it in `docs/source/configuration.rst`
- [ ] Please add a test for your change. Tests can be run in the commandline
      with `make check` or you can run them in the browser by running `make serve`
      and then opening `http://localhost:8000/tests.html`.

### CODE REVIEW

File: src/headless/utils/url.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ export function getURI (url) {
 
 function checkFileTypes (types, url) {
     const uri = getURI(url);
-    if (uri === null || !checkTLS(uri)) {
+    if (window.location.protocol !== 'chrome-extension:' && (uri === null || !checkTLS(uri))) {
```
Comment (jcbrand) [inline src/headless/utils/url.js:24]: Looking at this again, I think this needs to be changed to:

`(uri === null || (window.location.protocol !== 'chrome-extension:' && !checkTLS(uri)))`

Otherwise, in a chrome extension, if `uri` is `null` a `TypeError` will be thrown on line 27.

**Comment by jcbrand** [comment]
Thanks!
