### PR TITLE
Fixes #2754

### LINKED ISSUE #2754: Navigation keys doesn't work anymore into chat input message
**Describe the bug**
Sometimes, but often after trying to edit a previous message, navigation keys into input message do not work anymore.
It is no more possible to use left key, for example, to position the cursor one letter before.

**To Reproduce**
It is been a while that I try to identify a reproductible case, but without success.
Has anyone ever got this behavior?

**Expected behavior**
Navigation keys always usable.

**Environment (please complete the following information):**
 - Desktop
 - Browser all common WEB browsers
 - Since Converse.js v7 (I don't know for previous versions)

**Additional context**
ConverseJS is used in overlayed mode.
<details>
  <summary>Initialization options</summary>

```
 converse.initialize({
          'view_mode' : 'overlayed',
          'i18n' : 'a language',
          'assets_path' : '/myserver/chat/converse/',
          'sounds_path' : '/myserver/chat/converse/',
          'play_sounds' : false,
          'bosh_service_url' : 'bosh url',
          'allow_logout' : false,
          'auto_login' : true,
          'auto_reconnect' : true,
          'jid' : 'a jid',
          'default_domain' : 'a domain',
          'domain_placeholder' : 'a domain',
          'password' : 'a password',
          'autocomplete_add_contact' : false,
          'notification_icon' : 'aLogo.png',
          'muc_domain' : 'conference.a.domain',
          'locked_muc_domain' : 'hidden',
          'muc_disable_slash_commands' : true,
          'locked_muc_nickname' : true,
          'nickname' : 'a nickname',
          'auto_register_muc_nickname' : true,
          'notify_all_room_messages' : true,
          'auto_join_on_invite' : false,
          'roster_groups' : false,
          'allow_adhoc_commands' : false,
          'allow_contact_removal' : false,
          'allow_contact_requests' : false,
          'allow_registration' : false,
          'show_controlbox_by_default' : false,
          'discover_connection_methods' : false
        });
```

</details>

### PR DESCRIPTION
**Pull request by SilverYoCha**
About https://github.com/conversejs/converse.js/issues/2754
That's a try.
Could maybe help to think about a better fix.

### CODE REVIEW

File: src/shared/chat/emoji-dropdown.js [hunk 1]
```diff
@@ -95,6 +95,12 @@ export default class EmojiDropdown extends DropdownBase {
         super.showMenu();
         setTimeout(() => this.querySelector('.emoji-search')?.focus());
     }
+
+    hideMenu () {
+        this.chatview.querySelector('converse-emoji-picker')?.disableArrowNavigation();
```
Comment (jcbrand) [inline src/shared/chat/emoji-dropdown.js:100]: In `src/shared/chat/emoji-picker.js` there is a function `_onGlobalKeyDown`. I think it would be better to listen for the escape key and then to call `disableArrowNavigation` there, instead of doing it here.

File: src/shared/chat/emoji-dropdown.js [hunk 2]
```diff
@@ -95,6 +95,12 @@ export default class EmojiDropdown extends DropdownBase {
...
+        super.hideMenu();
+        setTimeout(() => this.chatview.querySelector('.chat-textarea')?.focus());
```
Comment (jcbrand) [inline src/shared/chat/emoji-dropdown.js:102]: Why did you move this here? I think it's better to leave this line where it was (including the `setTimeout` if that is somehow necessary to fix a race condition).

This, coupled with the above change would mean that it's no longer necessary to overwrite `hideMenu` in this component.

**Comment by jcbrand** [comment]
Thanks for the PR @SilverYoCha :)

I've left two review comments.

**Review by jcbrand — CHANGES_REQUESTED** [review]

File: src/shared/chat/emoji-dropdown.js (hunk 2 above)
Comment (SilverYoCha) [reply src/shared/chat/emoji-dropdown.js:102]: Thank you @jcbrand for the consideration of my PR.

There are several use cases with the emojis drop down concerning its closing. All these use cases do not result in calling same code when closing the drop down.
For example, closing the drop down just after its opening by using ESCAPE key, calls `onKeyDown` method in `emoji-picker.js`. But after having navigated into emoji list, closing it by using ESCAPE key or by clicking outside the emoji drop down doesn't call the `onKeyDown` method.
My idea was to find a method which was performed whatever the closing case. It seems to be the case of `hideMenu` method of `emojis-dropdown.js` (by overriding). I found that it was not so bad to centralize the closing stuffs into this method, and so I overrided it. 

That being said, I can try your suggestions.

Comment (SilverYoCha) [reply src/shared/chat/emoji-dropdown.js:102]: It seems to be same problematics with `_onGlobalKeyDown` method. It is not called whatever the context into which the emoji drop down is closed.

Comment (jcbrand) [reply src/shared/chat/emoji-dropdown.js:102]: Ok. The reason I made my suggestions, is because I'd like to reduce the usage of imperative code where for example we call `querySelector` to call methods on components and because ideally we should decouple components from one another and have the components be as declarative as possible (i.e. more like React and less like jQuery).

In other words, I think it's an anti-pattern to continuously use things like `this.chatview`, because it tightly couples this component to the component referenced by `this.chatview`. The reason why we still use `this.chatview` in various places is because it was the quickest way to turn all the backbone views into web components. But ideally we should try and get the components as independent of one another as possible and remove the usage of `this.chatview` where ever it's still used.

I think eventually we probably will move the emoji picker component into a separate NPM package (and perhaps a separate Github repo), and in that case we won't be able to rely on `this.chatview`.

Comment (SilverYoCha) [reply src/shared/chat/emoji-dropdown.js:102]: I understand your aim and I agree with it.
Unfortunately, my knowing of the entire of the project, and more generally of JavaScript framework universe, are not enough to propose better for now.
Don't hesitate to close my PR without merging it.
I tried :-)
Thank you @jcbrand.

Comment (jcbrand) [reply src/shared/chat/emoji-dropdown.js:102]: No worries, I've merged your commit and then did some refactoring to bring things more in line with the goals stated above.

Can you please check whether things still work for you as expected?

**Comment by deleolajide** [comment]
>Can you please check whether things still work for you as expected?

I can't reproduce the issue with this commit, but my testing is not exhaustive. I will watch out for it over the next few days as it used to occur enough to notice for me

File: src/shared/chat/emoji-dropdown.js (hunk 2 above)
Comment (SilverYoCha) [reply src/shared/chat/emoji-dropdown.js:102]: Things are still working as expected :-)
:+1:
