### PR TITLE
Prevent tranforming malformed urls and urls with non-approved protocols into hyperlinks

### LINKED ISSUE #2019: Insecure and malformed URLs are being parsed as correct.
**Describe the bug**
Insecure and malformed URLs are being parsed as correct.

**To Reproduce**
1. Open a chat window
2. Type wrong and unsafe URLs and see them getting parsed as correct:
- http://#$%^&*(&%$$%^&*
- file://evil.sh

Screen Shot 2020-05-04 at 8 04 14 PM

**Expected behavior**
Not parsing malformed or insecure URLs

### PR DESCRIPTION
**Pull request by afuggini**
Fixes #2019 

Screen Shot 2020-05-04 at 7 48 17 PM

### CODE REVIEW

File: src/utils/html.js [hunk 1]
```diff
@@ -403,14 +399,41 @@ u.convertToHyperlink = function (url) {
...
+        const url = new URL(urlString);
+        return !!url;
+    } catch (error) {
+        return false;
+    }
 }
 
+u.convertUrlToHyperlink = function (url) {
+    const uri = getURI(url);
+    if (uri !== null && isUrlValid(url) && isProtocolApproved(uri._parts.protocol)) {
```
Comment (jcbrand) [inline src/utils/html.js:420]: The `uri !== null` check can go into `isUrlValid`, after all, `null` isn't a valid URL :)

Generally in the Converse codebase we write abbreviations as all-caps. So `isURLValid` instead of `isUrlValid`.

File: src/utils/html.js [hunk 2]
```diff
@@ -388,13 +389,8 @@ u.addMentionsMarkup = function (text, references, chatbox) {
     return text;
 };
 
-
-u.convertToHyperlink = function (url) {
-    const uri = getURI(url);
-    if (uri === null) {
-        return url;
-    }
```
Comment (jcbrand) [inline src/utils/html.js:396]: It's not clear to me why you removed these lines, can you please explain why?

**Comment by jcbrand** [comment]
@afuggini: I see your changes have introduced a test failure. Please fix.

https://travis-ci.org/github/conversejs/converse.js/builds/683193248#L2230

File: src/utils/html.js (hunk 1 above)
Comment (afuggini) [reply src/utils/html.js:420]: `uri` is not a url string, but an instance of the `URI` class, whereas the purpose of `isUrlValid` is to check for valid url strings. I moved this check to here from the code that you commented on below, which was then removed.

File: src/utils/html.js (hunk 2 above)
Comment (afuggini) [reply src/utils/html.js:396]: This `uri === null` check is now part of line `420`.

**Comment by afuggini** [comment]
Added fixes and tests

**Comment by afuggini** [comment]
@jcbrand Added fixes and tests. However, I still see errors... would you please shed some light on those?

File: src/utils/html.js (hunk 1 above)
Comment (jcbrand) [reply src/utils/html.js]: Ah sorry, I see now they're two different variables.

**Comment by jcbrand** [comment]
Thanks @afuggini I restarted the build on Travis and now all tests are green.
